### ISSUE TITLE
Makefile: modify to use a correct compiler for C

### ISSUE THREAD

**Issue by MartinCupak** [ADACS-Australia/beans#1]
* Operating System: Linux Ubuntu 20.04 LTS

### Description

Modify makefile to use gcc to compile C code, not g++ for all code.

Note: this was actually anabling C++ functionality in supposedlt C language code, particularly overloading functions

### What I Did

```
linux: settle.o 
	gcc -Ofast -fPIC -c *.c
	g++ -Ofast -fPIC -c *.cc
```

**Comment by MartinCupak** [comment]
Consequence: the test will not pass, as in the library, there are references to undefined functions

Settle test...
Traceback (most recent call last):
  File "try.py", line 8, in <module>
    settl = se.settle()
  File "/home/martin/src/CIC/Adele/beans/settle/settler.py", line 39, in __init__
    self.libsettle = ct.cdll.LoadLibrary("/usr/local/lib/libsettle.so")
  File "/home/martin/miniconda3_py38/envs/beans/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/martin/miniconda3_py38/envs/beans/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libsettle.so: undefined symbol: _Z6matrixllll

**Comment by MartinCupak** [comment]
Need to add extern "C" { } directive for calling C from C++ (wrap #include headeres)

**Comment by MartinCupak** [comment]
done as per https://stackoverflow.com/questions/16850992/call-a-c-function-from-c-code
